### PR TITLE
feat: Adds a code coverage build profile.

### PR DESCRIPTION
**Pull request by gpolitis**

### CODE REVIEW

**Review by JonathanLennox — DISMISSED** [review]

**Comment by ibauersachs** [comment]
What is happening with the coverage results? Wouldn't it make sense to activate the profile in the Actions workflow and adding Codecov? Or is that coming in a follow-up? (Same for -utils)

**Comment by gpolitis** [comment]
> What is happening with the coverage results? Wouldn't it make sense to activate the profile in the Actions workflow and adding Codecov? Or is that coming in a follow-up? (Same for -utils)

I've discussed this with various people in slack and we can use the reports in Jenkins, potentially failing a PR if it reduces the code coverage pct. @bbaldino mentioned Codecov but we'd have to buy a paid plan (as we have > 5 users so the basic plan presumably doesn't cover us) and we don't want to go down that road. I admit I may have misunderstood their pricing model though and I would be happy to look into it again if you think we can use the basic plan.

**Comment by ibauersachs** [comment]
Codecov has this in small print below their Basic plan: `*Open Source? Free for unlimited users and repos`. So I don't see a problem with using Codecov for coverage.

I started using SonarCloud for [dnsjava](https://github.com/dnsjava/dnsjava) (-> https://sonarcloud.io/project/issues?id=dnsjava_dnsjava). That might be an option here as well. Unfortunately, they don't have a GitHub app yet so the reports only work on branches/PRs within the repo (i.e. not from forks). If an internal SonarQube instance is still required if SonarCloud is use, you could run the builds on a separate, isolated Jenkins that has access to the private SonarQube.

**Comment by gpolitis** [comment]
> Codecov has this in small print below their Basic plan

That's exciting, thanks @ibauersachs! 

> I started using SonarCloud for dnsjava

Codecov seems easier to setup so I'm wondering why did you chose SonaQube instead of Codecov for dnsjava? Was Codecov not available at the time or was it more of a technical choice? 

> If an internal SonarQube instance is still required if SonarCloud is use

Definitely not required, not at this point at least.

**Comment by ibauersachs** [comment]
> > Codecov has this in small print below their Basic plan
> 
> That's exciting, thanks @ibauersachs!
> 
> > I started using SonarCloud for dnsjava
> 
> Codecov seems easier to setup so I'm wondering why did you chose SonaQube instead of Codecov for dnsjava? Was Codecov not available at the time or was it more of a technical choice?

I actually use both:
- SonarCloud for those who can push directly to the repo
- Codecov for pull requests from forks

I'd prefer using only Sonar because it provides much more analysis than just coverage, but that's currently not possible without making the secret to publish the report public. There's a [thread in the Sonar forum](https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/11) and a [tracking issue](https://jira.sonarsource.com/browse/MMF-1371).

> > If an internal SonarQube instance is still required if SonarCloud is use
> 
> Definitely not required, not at this point at least.

**Comment by gpolitis** [comment]
@ibauersachs thanks for the insight, we can probably start with Codecov now and setup SonarQube later. I've modelled the changes after jitsi-metaconfig. I'm wondering if there's anything else we can do here ?

**Comment by JonathanLennox** [comment]
So when I click on the link that says "Continue to review full report at Codecov." I get an error page.  Is this something that can/should be fixed before we merge this?

**Comment by gpolitis** [comment]
> So when I click on the link that says "Continue to review full report at Codecov." I get an error page. Is this something that can/should be fixed before we merge this?

I think it's because there's no base line? i.e. we're just starting to upload coverage repots. I'm not 100% sure though :/

**Review by ibauersachs — APPROVED** [review]
LGTM, the comment with the missing base branch should go away as soon as this hits master.

**Comment by gpolitis** [comment]
Great, thank you Ingo.

**Pull request merged**
