### PR TITLE
WIP: Additional platforms and cmake build

### PR DESCRIPTION
**Pull request by mstyura**

### CODE REVIEW

**Comment by mstyura** [comment]
Hello @JonathanLennox,

Could you please take a brief look at this PR and tell me what do you think on approach of native/java interop implemented (similar to what was done in jitsi-sctp)?
The most significant change is putting native code into dedicated platform specific artifact hosted on maven, rather than precompiled library stored in git. This required splitting single artifact into 3 sub-artifacts: java-only, native platform specific, mixed - merged native and java-only artifacts.
I think it would be easier to look at local clone of my fork, rather than understand from diff on github.

**Comment by JonathanLennox** [comment]
What is the purpose of having three separate artifacts?  (I'm not saying it's necessarily a bad idea, I'm just wondering what the goal is.)

**Comment by mstyura** [comment]
@JonathanLennox  the goal was to put native library for each supported platform into dedicated artifact and put into maven, and remove precompiled version from git. 
For example, this will allow other people fixing native compilation settings or code for their purpose and send PR, and it will not require someone trusted to compile new native binary to put it under git. Trusted `Jenkins` job will build and publish new artifact automatically. Right now even fixing native warnings will require coordination with someone who is eligible of re-building native library and putting it into git.

So there could be several version of `jitsi-srtp-native` artifact for each supported platform like `jitsi-srtp-native-{version}-linux-x86-64.jar`, `jitsi-srtp-native-{version}-darwin.jar`, `jitsi-srtp-native-{version}-linux-arm64.jar`.
Another maven module`jitsi-srtp-java` it for pure java code which also have methods marked with `native`, this module compiled into `jar` which has classes and enriched with `C` header files necessary to implement native methods.
`jitsi-srtp-native` depends on `jitsi-srtp-java`, because of headers.
Then third module is `jitsi-srtp` which is basically `jitsi-srtp-java` combined with `jitsi-srtp-native` for one or more native platforms to produce an artifact which has both java classes and compiled native libraries for supported platforms.

PS. Migration to `CMake` itself could be done with same project structure. If this PR is too much changes I could create another one migrating native compilation to `CMake`.

**Comment by JonathanLennox** [comment]
Oh, I see -- so your idea is that any given platform uses either jitsi-srtp.jar (if it's an officially supported platform), or jitsi-srtp-java.jar plus the appropriate jitsi-srtp-native.jar (if it's not)?

**Comment by licaon-kter** [comment]
Any news?

**Comment by ibauersachs** [comment]
Wouldn't this be substantially simpler if
- build with Github actions
- osx: assume having brew, so OpenSSL can be located with a CMake builtin
- linux: which version of OpenSSL should be supported anyway?
- other platforms: run a docker container

Are pure java and single platforms jars really required? Putting all architectures into a single jar would be much easier (to build and for consumers).

**Comment by mstyura** [comment]
@ibauersachs i’m currently working on adding github actions on top this PR. It take longer than I initially planned both because I was not familiar with GH actions and due lack of enough free time.

**Comment by licaon-kter** [comment]
Any news?

**Comment by ibauersachs** [comment]
I'm in favor of closing this and do smaller improvements on top of #22:
- Add GitHub actions
- Build the published jar from source, including the native lib
- Maybe
  * Remove the pre-built native. Anyone who is working on the lib is likely to required to build the native part anyway as well. In the rare case where it is required without building locally, a binary can be extracted from a previous version.
  * Add CMake build files this instead of the convoluted Maven native build

Other platforms are not as important as they once might have been: using JDK 11 there is no performance gain whatsover with the OpenSSL implementation AES/CTR anymore and with AES/GCM it is negligable for most use cases.

**Comment by licaon-kter** [comment]
@mstyura Can you update though? jvb needs latest jitsi-srtp since https://github.com/jitsi/jitsi-videobridge/commit/430a435f33bd7342019c1682abd02639a3870bfd else video does not pass through and it just outputs this ~~error~~warning:
> WARNING: [71] [confId=354e8572e148091 epId=18061355 gid=66712 stats_id=Landen-cNk conf_name=roomname@meet.domain.tld] PacketParser.transform#36: Error parsing packet: org.jitsi.rtp.rtcp.CompoundRtcpContainedInvalidDataException: Compound RTCP contained invalid data.  Compound RTCP packet data is: 80C90001 DB389BFD 766B0574 F762EB06
52FBCCDE AACB1DF6 80000009  Invalid data started at offset 8 and failed due to 'length 5588 > available 20'
```

**Pull request closed without merging**
